# Generated by Django 2.0.2 on 2018-02-28 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('ticker', models.CharField(max_length=50)),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('opening', models.FloatField()),
                ('closing', models.FloatField()),
                ('volume', models.IntegerField()),
                ('date', models.DateField()),
            ],
        ),
    ]
