# Generated by Django 2.0.2 on 2018-03-14 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=50)),
                ('company_name', models.CharField(max_length=100, unique=True)),
                ('exchange', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=50)),
                ('prediction', models.FloatField(blank=True, default=0)),
                ('date_ran_experiment', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('ticker', models.CharField(max_length=50)),
                ('high', models.FloatField(blank=True, default=0)),
                ('low', models.FloatField(blank=True, default=0)),
                ('opening', models.FloatField(blank=True, default=0)),
                ('closing', models.FloatField(blank=True, default=0)),
                ('volume', models.IntegerField(blank=True, default=0)),
                ('date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
