# Generated by Django 2.0.2 on 2018-02-28 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_auto_20180228_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='closing',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='stock',
            name='high',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='stock',
            name='low',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='stock',
            name='opening',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='stock',
            name='volume',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
