image: python:3.6

stages: 
    - setup 
    - test
    - deploy

before_script: 
    - apt-get update -qq 

setup: 
    stage: setup
    script: 
        - pip install -r requirements.txt 

test: 
    stage: test
    only: 
        - test_ci 
    script: 
        - coverage run manage.py test stocks
        - coverage report
        - coverage html 

deploy: 
    stage: deploy
    only: 
        - test_ci 
    script: 
        - pip install azure-cli 
        - echo -e "[INFO] Currently testing out with docker deploy." 
