stages: 
    - build
    - test
    - deploy

job1.0: 
    stage: test
    only: 
        - master
    script:
        - cd /home/gitlab-runner/builds/cdbdb0ba/0/prodigal/pro-ml/data_mine
        - python -m pytest -s -v tests/

