stages: 
    - build
    - test
    - deploy

job1.0: 
    stage: build
    only: 
        - hk_iteration3
    script:
        - cd /home/gitlab-runner/builds/d82fbb85/0/prodigal/pro-ml/data_mine
        - python -m pytest -s -v tests/
