stages: 
    - build
    - test_datamine

build: 
    only: 
        - hk_iteration3
    script:
        - echo "Now is building." 

test_datamine: 
    only: 
        - hk_iteration3
    script: 
        - cd /home/ec2-user/workspace/pro-ml
        - source env/bin/activate
        - python -m pytest -s -v tests/
