image: python:3.6

stages: 
    - test
    - deploy

before_script: 
    - apt-get update -qq 
    - pip install -r $(find `pwd` -iname "requirements.txt")

test: 
    stage: test
    only: 
        - test_ci 
    script: 
        - coverage run $(find `pwd` -iname "manage.py") test stocks
        - coverage report
        - coverage html 

deploy: 
    stage: deploy
    only: 
        - test_ci 
    script: 
        - pip install azure-cli 
        - echo -e "[INFO] Currently testing out with docker deploy." 
