stages: 
    - build
    - test

build: 
    only: hk_iteration3
    script:
        - echo "Now is building." 

test: 
    only: hk_iteration3
    script: 
        - cd /home/ec2-user/workspace/pro-ml
        - source env/bin/activate
        - pytest -s -v 
