before_script: 
    - export PATH=$PATH:/usr/local/bin:/home/gitlab-runner/python/bin
    - pip3 install pytest Django==2.0.2 djangorestframework mysqlclient

stages: 
    - build
    - test
    - deploy

job_test1: 
    stage: test
    only: 
        - hk_iteration4
    script:
        - cd /home/gitlab-runner/builds/924d7679/0/prodigal/pro-ml/backend
        - python manage.py test

job_deploy: 
    stage: deploy
    only: 
        - master
    script:
        - cd /home/gitlab-runner/builds/924d7679/0/prodigal/pro-ml/backend
        - eb deploy
