stages: 
    - build
    - test
    - deploy

job1.0: 
    stage: build
    only: 
        - hk_iteration3
    script:
        - pip install pytest
        - cd /home/gitlab-runner/builds/d82fbb85/0/prodigal/pro-ml

job1.1: 
    stage: test
    only: 
        - hk_iteration3
    script: 
        - cd data_mine
        - python -m pytest -s -v tests/
        - cd ..

job1.2: 
    stage: test
    only: 
        - hk_iteration3
    script:
        - cd web_service 
        - python -m pytest -s -v tests/
        - cd ..

